### ISSUE TITLE
Medical concept vocabulary to enable analysis on different EHR datasets

### ISSUE THREAD

**Issue by kapka2** [landiisotta/convae_architecture#1]
I would like to apply the ConvAE method to another EHR dataset.  In order to do this, having the vocabulary of medical concepts would be necessary.  Would you be willing to share this vocabulary?

**Comment by landiisotta** [comment]
Dear @kapka2 , I'm not sure I understand. The vocabulary of terms used by the algorithm can be anything and it's needed to create the input vectors. So you should use the vocabulary obtained from your dataset of interest. Is this what you were referring to?

**Comment by kapka2** [comment]
Dear @landiisotta,
Yes I have seen that the code is flexible to handle arbitrary vocabularies, which is great.  I would like to see if I can replicate the findings from the publication, Deep representation learning of electronic health records to unlock patient stratification at scale, using a different EHR dataset.  Would it be possible to share the vocabulary of medical concepts used in that publication?

**Comment by landiisotta** [comment]
Dear @kapka2,
we are happy to share the vocabulary for replication. Could you please email us at isotta.landi2@mssm.edu and riccardo.miotto@mssm.edu with your request and a detailed description of your project? Thank you!

**Comment by kapka2** [comment]
Many thanks, will share the project proposal shortly.
