### ISSUE TITLE
Loading of precomputed word2vec embeddings, and refinement during training

### ISSUE THREAD

**Issue by EricNeville** [landiisotta/convae_architecture#2]
As far as I can tell the precomputed word2vec embeddings are not being loaded as the model is currently written. In model.py we have :
``` python
# load pre-computed embeddings
cnd_emb = pre_embs is not None
cnd_vocab = vocab is not None
if cnd_emb and cnd_vocab:
    weight_mtx = np.zeros((vocab_size, emb_size))
    wfound = 0
    for i in range(vocab_size):
        if i != 0:
            try:
                weight_mtx[i] = pre_embs[vocab[i]]
                wfound += 1
            except KeyError:
                weight_mtx[i] = np.random.normal(
                    scale=0.6, size=(emb_size,))
    print('Found pre-computed embeddings for {0} concepts'.format(
        wfound))
    self.embedding.from_pretrained(torch.FloatTensor(weight_mtx))
```

The final line does not update the existing `self.embedding`, instead it returns the pretrained embedding. It needs to be reassigned:
```python
self.embedding = self.embedding.from_pretrained(torch.FloatTensor(weight_mtx))
```

As currently written the `weight_mtx` is computed then never used, and the embedding portion of the network starts from random initialisation and is trained as part of the model. Making the above change preloads the computed embeddings, but `self.embedding.from_pretrained()` also includes `freeze = True` by default, so with the above change the precomputed embeddings are loaded and then remain fixed during training. In the paper you say "These embedding vectors were then used as input for the ConvAE module and were further refined during the model training." Therefore it seems that what this line should be is:
```python
self.embedding = self.embedding.from_pretrained(torch.FloatTensor(weight_mtx), freeze = False)
```

**Comment by landiisotta** [comment]
Hi @EricNeville, thank you so much for spotting the issue, you're absolutely right, I fixed the code as per your suggestion.
